App:
  Id: 1
  # 调试模式
  DebugMode: true
  # 分布式
  IsDistributed: false
  # 1 开发环境 2 线上环境
  Environment: 2
  # 项目统一前缀
  Prefix: go-com
  # 运行时的缓存文件目录 空表示：项目目录/runtime
  RuntimePath:

  # api 地址
  ApiAddr: 0.0.0.0:9701
  # web_api 地址
  WebApiAddr: 0.0.0.0:9702
  # kafka消费是否写入日志
  KafkaToLog: true
  # 最大延迟队列消费者数目
  MaxDelayQueueConsumeWorkerNum: 100
  # 延迟队列消息最大缓存时间 秒
  MaxDelayQueueTimeout: 86400

  # 网关地址
  GatewayAddr: http://192.168.2.187:19080
  # 网关token
  GatewayToken: K00hRvlnNw3DJNWWIeODwjwyBOafBn8u

Pgsql:
  Host: 192.168.2.70
  Port: 5432
  User: postgres
  Password: mypass
  Dbname: alarm_center
  MaxOpenConns: 200
  MaxIdleConns: 10