App:
  # 在当前服务下的唯一编号，每启动一个服务程序都要配置，最大1023
  Id: 1
  # 调试模式（日记级别：debug）
  DebugMode: true
  # 分布式
  IsDistributed: false
  # 1 开发环境（打印sql日志） 2 线上环境
  Environment: 1
  # 项目统一前缀
  Prefix: go-com
  # 运行时的缓存文件目录 空表示：项目目录/runtime
  RuntimePath:

  # 公网IP（用于外网机器人访问）
  PublicIp: 192.168.2.70
  # api 地址
  ApiAddr: 0.0.0.0:9701
  # web_api 地址
  WebApiAddr: 0.0.0.0:9702
  # kafka消费是否写入日志
  KafkaToLog: true
  # kafka最大消费者数目
  MaxKafkaConsumeWorkerNum: 10

  # 网关token
  GatewayToken: K00hRvlnNw3DJNWWIeODwjwyBOafBn8u
  # 网关地址
  GatewayAddr: http://192.168.2.70:9080
  # 开放目录 空表示：项目目录/runtime/public
  PublicPath:
  # 文件上传大小限制 单位Mb
  MaxMultipartMemory: 1024
  # grpc访问地址
  GrpcAddr: 0.0.0.0:9703
  # grpc鉴权token
  GrpcToken: K00hRvlnNw3DJNWWIeODwjwyBOafBn8u
  # 延迟队列消费轮询周期，单位s
  DelayQueueConsumePeriod: 5
  # 延迟队列持久化轮询周期，单位s
  DelayQueuePersistPeriod: 10

Postgresql:
  Host: 192.168.2.70
  Port: 5432
  User: postgres
  Password: mypass
  Dbname: test
  MaxOpenConns: 200
  MaxIdleConns: 10

Clickhouse:
  Addr: 192.168.2.70:9000
  User: itestor
  Password: 36h2E5paQhQ6Bc8C
  Dbname: test

Kafka:
  Servers: 192.168.2.22:9092
  Username:
  Password:
  Topic: for-test
  Group: test-group6
  SecurityProtocol:
  SaslMechanisms:

Mysql:
  Addr: 192.168.2.70:3306
  User: root
  Password: mypass
  Dbname: phoenix_v2_auth
  DbConfig:
    Prefix:
    ConnMaxLifetime: 180
    MaxOpenConns: 200
    MaxIdleConns: 10

Redis:
  Addr: 192.168.2.70:6379
  Password: mypass
  Db: 0

Etcd:
  Addr:
    - 192.168.2.70:12379
  User: root
  Password: mypass
  CertFile:
  KeyFile:
  TrustedCAFile: