App:
  # 在当前服务下的唯一编号，每启动一个服务程序都要配置，最大1023
  Id: 1
  # 调试模式（日记级别：debug）
  DebugMode: true
  # 分布式
  IsDistributed: false
  # 1 开发环境（打印sql日志） 2 线上环境
  Environment: 1
  # 项目统一前缀
  Prefix: go-com
  # 运行时的缓存文件目录 空表示：项目目录/runtime
  RuntimePath:
  # 日志有效期，单位天
  LogExpire: 10

  # 公网IP（用于外网机器人访问）
  PublicIp: 192.168.2.70
  # api 地址
  ApiAddr: 0.0.0.0:9701
  # web_api 地址
  WebApiAddr: 0.0.0.0:9702

  # 网关token
  GatewayToken: K00hRvlnNw3DJNWWIeODwjwyBOafBn8u
  # 网关地址
  GatewayAddr: http://192.168.2.70:9080
  # 开放目录 空表示：项目目录/runtime/public
  PublicPath:
  # 文件上传大小限制 单位Mb
  MaxMultipartMemory: 1024
  # grpc访问地址
  GrpcAddr: 0.0.0.0:9703
  # grpc鉴权token
  GrpcToken: K00hRvlnNw3DJNWWIeODwjwyBOafBn8u

Postgresql:
  Host: 192.168.2.70
  Port: 5432
  User: postgres
  Password: mypass
  Dbname: test
  MaxOpenConns: 200
  MaxIdleConns: 10

Clickhouse:
  Addr: 192.168.2.70:9000
  User: itestor
  Password: 36h2E5paQhQ6Bc8C
  Dbname: test

Kafka:
  Servers: 192.168.2.22:9092
  Username:
  Password:
  Topic: for-test
  Group: test-group6
  SecurityProtocol:
  SaslMechanisms:
  # kafka消息消费日志有效期，单位天，0表示不记录
  LogExpire: 10
  # kafka最大消费者数目
  MaxConsumeWorkerNum: 10

Mysql:
  Addr: 192.168.2.70:3306
  User: root
  Password: mypass
  Dbname: phoenix_v2_auth
  DbConfig:
    Prefix:
    ConnMaxLifetime: 180
    MaxOpenConns: 200
    MaxIdleConns: 10

Redis:
  Addr: 192.168.2.70:6379
  Password: mypass
  Db: 0

Etcd:
  Addr:
    - 192.168.2.70:12379
  User: root
  Password: mypass
  CertFile:
  KeyFile:
  TrustedCAFile:

Nebula:
  Host: 192.168.2.71
  Port: 9669
  User: root
  Password: 123456
  Dbname: tyhd_net

Es:
  Addr:
    - http://127.0.0.1:29042
  User: elastic
  Password: e49S^cQG7m
  DbConfig:
    MaxOpenConns: 200
    MaxIdleConns: 10

RateLimit:
  # 桶中每秒产生token个数
  Limit: 4
  # 桶中token最大个数
  Burst: 5
  # 桶中token耗尽后等待刷新token时长，单位ms
  Timeout: 1000
  # 桶外token存量最大个数
  MaxStock: 10

RateBreaker:
  # 一个周期的时长，单位s
  Interval: 300
  # 打开到半开持续的时长，单位s
  OpenTimeout: 10
  # 最大请求次数：半开时，与Requests、ConsecutiveSuccesses比较
  HafMaxRequests: 50
  # 关闭到打开，一个周期内最小请求次数
  CloseMinRequests: 5
  # 关闭到打开，一个周期内错误百分比，单位%
  CloseErrorPercent: 30

Dq:
  # 延迟队列消费轮询周期，单位s
  ConsumePeriod: 10
  # 延迟队列持久化轮询周期，单位s
  PersistPeriod: 0
  # 最大并行数目，0表示串行
  MaxWorkerNum: 100
  # 是否判断消息的no是否存在
  CheckNoExist: true
